<a href="https://colab.research.google.com/github/prd-dahal/AI_Projects/blob/master/Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Week 2 Practice**


In [0]:
import numpy as np
import math


#defination of sigmoid function
def sigmoid(x):
  return 1/(1+math.pow(2.71828,-x))

#defination of output function where w is array of weight and x is array of inputs and b is the bias
def output(w,x,b):
  return sigmoid(((np.transpose(w)*x).sum()+b))

#defination of log fuction as log 0 myst give -infinite value 
def log(x):
    if(x==0):
      return -(99999)
    else:
      return math.log(x)

#defination of cost function where y and y_cap  are numpy arrays of dimension 1 * nx where nx is 
#the number of features
def cost_function(y, y_cap):
  m = len(y)
  temp_y_cap = list()
  temp_y_cap1 = list()
  for i in y_cap:
    temp_y_cap.append(log(i))
    temp_y_cap1.append(log(1-i))
  
  temp_y_cap = np.array(temp_y_cap)
  temp_y_cap1 = np.array(temp_y_cap1) 
  
  temp_cost = (y*temp_y_cap)+ (1-y)*temp_y_cap1
  temp_cost = -(temp_cost.sum())
  return (-1/m)*temp_cost

#main function exceution
y = np.array([1, 0, 1])
y_cap = np.array([1, 1, 1])
print(cost_function(y,y_cap))

w = np.array([[1],[2],[3]])
x = np.array([[1, 2, 3]])
b = 3



33333.0


# **Logistic Regression USING LOOPS ( i.e Without Vectorization**


In [0]:
#Following Code is not the efficient code but rather a make it work kind of code.



import numpy as np
import random 

class LogisticRegression:
  
  def __init__(self,num_iter,alpha):
    self.num_iter = num_iter
    self.alpha = alpha
    self.weights = list()
    self.b = float()

  #private function to calculate sigmoid
  def __sigmoid(self,x):
    return 1/(1+np.exp(x))
  
  #fit the object with the training data X and y
  def fit(self,X,y):
    nx = len(X[0]) # no of features
    m = len(X)    #no of training examples

    #intitialize all weights to zero
    for i in range(nx):
      self.weights.append(random.randint(-10,10))
    self.b = random.randint(-10,10)

    for t in range(self.num_iter): #loop unitil the number of interation provided by user
      
      #variable intialization
      z = list()
      a = list()
      J = 0
      dw = list()
      db = 0
      
      for i in range(m):
       
        z.append(np.dot(X[i],self.weights) + self.b)
        a.append(self.__sigmoid(z[i]))
        J = J +  (- ((y[i]*np.log(a[i]))))
        dz = a[i]-y[i]
        
        for j in range(nx):
          if (i==0):
            dw.append((X[i][j] * dz))
          else:
            dw[j] = dw[j] + (X[i][j] * dz)
        db = db + a[i] - y[i]
      
      for i in range(nx):
         dw[j] = dw[j]/m
      
      J = J/m
      db = db/m
      
      for i in range(len(self.weights)):
         self.weights[i] = self.weights[i] - self.alpha * dw[i] 
      

#main function
feature_x = [[1,2,3],
             [3,4,5],
             [6,7,8]]
result_y = [1,0,1]

lr = LogisticRegression(5,0.1)
lr.fit(feature_x,result_y)

### Vectorization

In [0]:
import time 
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
print(c)
toc = time.time()

print("It took {}ms".format(1000*(toc-tic)))

sum=0
tic1 = time.time()
for i in range(len(a)):
  sum = sum + a[i] * b[i]
print(sum)
toc1 = time.time()

print("It took {}ms".format(1000*(toc1-tic1)))


print("Vectorization is {} times faster".format((toc1-tic1)/(toc-tic)))

250074.12538953198
It took 1.734018325805664ms
250074.12538952183
It took 655.620813369751ms
Vectorization is 378.09335899903755 times faster


## Broadcasting in python

In [0]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
# print(A)
print(A.sum(axis=0))
print(A.sum(axis=1))

[ 59.  239.  155.4  76.9]
[128.4 165.2 236.7]


# **Logistic Regression Using Vectorization ***

In [0]:
import numpy as np
import time

class VLogisticRegression:
  def __init__(self, num_iter, alpha, verbose = 0,tolerance = 0.00000000000001):
    self.num_iter = num_iter
    self.alpha = alpha
    self.weights = list()
    self.intercept = 0
    self.verbose = verbose
    self.tolerance = tolerance
    self.total_time = 999
  
  def __sigmoid(self,x):
    return 1/(1+np.exp(-x))

  def weights_(self):
    return self.weights #return array of weights 
  
  def intercept_(self):
    return self.intercept #return intercept/b value
  
  def time_to_fit(self):
    return self.total_time
  
  def predict(self,x):
    return self.__sigmoid(np.dot(self.weights,x) + self.intercept) #return the predicted value
  
  def fit(self,X,y): #fit function where X is the 2D matrix of size m*nx here m = no of training data and nx = no of feature in each  
    starting_time = time.time()
    nx = X.shape[1] 
    m = X.shape[0]
    dw = np.random.randn(nx)
    weights = np.random.randn(1,nx)
    b = np.random.randn(1,1)
    
    for i in range(self.num_iter):  # gradient descent loop
      Z = np.dot(weights, X.T) + b
      a = 1/(1+np.exp(-Z))
      dZ = a-y
      j = - (y * np.log(a) + (1-y)* np.log(1-a)) #error calculation
      J = np.mean(j)
      db = np.mean(dZ)
      dw = ((dZ.reshape(4,1) * X).sum(axis=0))/m
      weights = weights - (self.alpha * dw)
      b = b- self.alpha * db 
      if(self.verbose==1): #print the error in each iteration if verbose is set to 1
        print("The error at the interation {} is {}".format(i,J))
      if(J<self.tolerance): #break the iteration if the error is less than tolerance
        break;
    self.weights = weights
    self.intercept = b 
    
    end_time = time.time()
    self.total_time = (end_time - starting_time) * 1000

#Main Function 
if __name__ == '__main__':
  X = np.array([[1,2,3],
                [4,5,6],
                [8,9,10],
                [11,12,13]])
  y = np.array([1,0,1,1])
  VLR = VLogisticRegression(100,0.1, verbose=1,tolerance=0.1)
  VLR.fit(X,y)
  print("Weights:{}".format(VLR.weights_()))
  print("Intercept:{}".format(VLR.intercept_()))
  print("Prediction:{}".format(VLR.predict([4,5,6])))
  print("Time:{}ms".format(VLR.time_to_fit()))

The error at the interation 0 is 1.0763708583537959
The error at the interation 1 is 0.7225765347695396
The error at the interation 2 is 0.5311821149901664
The error at the interation 3 is 0.5278434808387594
The error at the interation 4 is 0.5287024610809044
The error at the interation 5 is 0.526564375078376
The error at the interation 6 is 0.5271892694378818
The error at the interation 7 is 0.5256293317434763
The error at the interation 8 is 0.5261418175400572
The error at the interation 9 is 0.5249037718886373
The error at the interation 10 is 0.5253678366033077
The error at the interation 11 is 0.5243230607252717
The error at the interation 12 is 0.5247786672673566
The error at the interation 13 is 0.5238530649772298
The error at the interation 14 is 0.524329566742001
The error at the interation 15 is 0.5234750274279005
The error at the interation 16 is 0.523997548940603
The error at the interation 17 is 0.5231787995479871
The error at the interation 18 is 0.523771789095732
The err

In [0]:
## HIT AND TIRAL FOR THE ALOGIRTHM ABOVE

X = np.array([[1,2,3],
              [4,5,6],
              [8,9,10],
              [11,12,13]])
y = np.array([1,0,1,1])
# print(X.shape[1])

weights = np.ones(3)
# print(weights)
b = np.ones(1)
Z = (np.dot(weights,X.T)+b)

a = 1/(1+np.exp(-Z))
# print(Z)
# print(a)
# print(y)
dZ = a-y
dw = (dZ.reshape(4,1)) * X
# print(dw)
dw = (dw.sum(axis=0))
# print(dw)
# print(dw/3)
# print(dz)
print(weights)
weights = weights - 0.1 * (dw)
print(weights)

[1. 1. 1.]
[0.60009115 0.50018227 0.40027338]


## 2 Layer Neural Network

In [0]:
import numpy as np
def sigmoid(x):
  return 1/ (1+np.exp(-x)) 
n_node = 4 
nx = 3 
feature_x = np.array([[2,3,4],
                      [3,4,5],
                      [7,8,9]])
W1 = np.random.randn(4,3)
print(W1)

feature_x = feature_x.T
print(feature_x)
Z =np.dot(W1  , feature_x) 
print(Z)

[[-1.53127221  0.91732151 -0.55024089]
 [ 0.13927189  3.00293509  2.11772257]
 [-1.56630397  1.34943927 -0.08199806]
 [-0.63398165 -0.62512628 -1.80590942]]
[[2 3 7]
 [3 4 8]
 [4 5 9]]
[[ -2.51154342  -3.675735    -8.33250131]
 [ 17.75823932  23.01816887  44.05788707]
 [  0.58771765   0.28885489  -0.90659614]
 [-10.36697981 -13.43199716 -25.69206654]]


# Multi Layer Neural Network

In [150]:
class NeuralNetwork:
  def __init__(self,no_of_node1, no_of_final_node, alpha, num_iter,verbose=0,threshold=0.00000001):
    self.no_of_node1 = no_of_node1
    self.no_of_final_node = no_of_final_node
    self.alpha = alpha
    self.threshold = threshold
    self.num_iter = num_iter
    self.W1 = list()
    self.b1 = list()
    self.W2 = list()
    self.b2 = list()
    self.m = 0
    self.nx = 0
    self.verbose = verbose
    
  #relu activation
  def __relu(self,Z):
    return np.maximum(0,Z)
  
  #sigmoid activation
  def __sigmoid(self,Z):
    return 1/(1+np.exp(-Z))
  
  #relu derivative activation
  def __reluDerivative(self,Z):
       Z[Z<=0] = 0
       Z[Z>0] = 1
       return Z
  #initialize the weights
  def __initialize_weight(self):
    self.W1 = np.random.randn(self.no_of_node1,self.nx) * 0.01
    self.b1 = np.random.randn(self.no_of_node1,1)
    self.W2 = np.random.randn(self.no_of_final_node, self.no_of_node1) * 0.01
    self.b2 = np.random.randn(self.no_of_final_node,1)
  
  def predict(self,X):
    Z1 = np.dot(self.W1,X) + self.b1
    
    A1 = self.__relu(Z1)
    Z2 = np.dot(self.W2,A1) + self.b2
    A2 = self.__sigmoid(Z2) 
    return A2.mean()
  def fit(self,X,y):
    self.nx = X.shape[0]
    self.m = X.shape[1]

    #initialize Weight
    self.__initialize_weight()
    for i in range(self.num_iter):
      ## START of forward Propagation
      Z1 = np.dot(self.W1,X) + self.b1
      
      #use of activation function
      A1 = self.__relu(Z1)
      
      #second layer calculation
      Z2 = np.dot(self.W2, A1) + self.b2
      A2 = self.__sigmoid(Z2) #output
      
      ## END of Forward Calculation

      #ERROR CALCULATION
      j = - (y * np.log(A2) + (1-y)* np.log(1-A2)) #error calculation
      J = j.mean()
      if(self.verbose==True):
        print("The error at this iteration {} is {}".format(i,J))
      if(J<self.threshold):
        break
      ##START OF BACKWARD CALCULATION
      dZ2 = A2-y
      dW2 = (1/self.m) * np.dot(dZ2 , A1.T)
      db2 = (1/self.m)* np.sum(dZ2,axis=1,)
      dZ1 = np.dot(self.W2.T,dZ2) * (self.__reluDerivative(Z1))
      dW1 = (1/self.m) * np.dot(dZ1,X.T)
      db1 = (1/self.m) * np.sum(dZ1, axis=1,keepdims=True)
      #END OF BACKWARD CALCULATOIN

      ## Update Weights
      self.W1 = self.W1 - self.alpha * dW1
      self.b1 = self.b1 - self.alpha * db1
      self.W2 = self.W2 - self.alpha * dW2
      self.b2 = self.b2 - self.alpha * db2

X = np.array([[1,2,3],
              [4,5,6],
              [8,9,10],
              [1,5,1],
              [2,3,4]])
X = X.T

y = np.array([1,0,1,1,1])

nn = NeuralNetwork(4,1,0.01,500, verbose=False,threshold=0.4)
nn.fit(X,y)

test = np.array([3,4,5])
predicted = nn.predict(test)
print(predicted)

0.8058638708689416


In [0]:
import numpy as np
X = np.array([[1,2,3],
              [4,5,6],
              [8,9,10],
              [11,12,13]])
X = X.T

y = np.array([1,0,1,1])
X.shape[0]
W1= np.ones((4,3))
b1 = np.ones((4,1))
W2 = np.ones((1, 4))
b2 = np.ones((1,1))


Z1 = (np.dot(W1,X))+b1

def relu(X):
    return np.maximum(0,X)


def sigmoid(Z):
    return 1/(1+np.exp(-Z))
# print(Z1)
A1= relu(Z1)


Z2 = np.dot(W2,A1) + b2
A2 = sigmoid(Z2)
j = - (y * np.log(A2) + (1-y)* np.log(1-A2)) #error calculation

J = j.mean()

dZ2 = np.dot(A2,y)

dW2 = (1/4)*dZ2 *  A1.T
def reluDerivative(Z):
       Z[Z<=0] = 0
       Z[Z>0] = 1
       return Z
print(reluDerivative(Z1))  
dZ1 = np.dot(W2.T,dZ2) * reluDerivative(Z1)


dW1 = (1/4) * np.dot(dZ1,X.T)

db1 = (1/4) * np.sum(dZ1, axis=1,keepdims=True)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: RuntimeWarning: divide by zero encountered in log
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:30: RuntimeWarning: invalid value encountered in multiply
