<a href="https://colab.research.google.com/github/prd-dahal/AI_Projects/blob/master/Neural_Networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Week 2 Practice**


In [0]:
import numpy as np
import math


#defination of sigmoid function
def sigmoid(x):
  return 1/(1+math.pow(2.71828,-x))

#defination of output function where w is array of weight and x is array of inputs and b is the bias
def output(w,x,b):
  return sigmoid(((np.transpose(w)*x).sum()+b))

#defination of log fuction as log 0 myst give -infinite value 
def log(x):
    if(x==0):
      return -(99999)
    else:
      return math.log(x)

#defination of cost function where y and y_cap  are numpy arrays of dimension 1 * nx where nx is 
#the number of features
def cost_function(y, y_cap):
  m = len(y)
  temp_y_cap = list()
  temp_y_cap1 = list()
  for i in y_cap:
    temp_y_cap.append(log(i))
    temp_y_cap1.append(log(1-i))
  
  temp_y_cap = np.array(temp_y_cap)
  temp_y_cap1 = np.array(temp_y_cap1) 
  
  temp_cost = (y*temp_y_cap)+ (1-y)*temp_y_cap1
  temp_cost = -(temp_cost.sum())
  return (-1/m)*temp_cost

#main function exceution
y = np.array([1, 0, 1])
y_cap = np.array([1, 1, 1])
print(cost_function(y,y_cap))

w = np.array([[1],[2],[3]])
x = np.array([[1, 2, 3]])
b = 3



33333.0


# **Logistic Regression USING LOOPS ( i.e Without Vectorization**


In [0]:
#Following Code is not the efficient code but rather a make it work kind of code.



import numpy as np
import random 

class LogisticRegression:
  
  def __init__(self,num_iter,alpha):
    self.num_iter = num_iter
    self.alpha = alpha
    self.weights = list()
    self.b = float()

  #private function to calculate sigmoid
  def __sigmoid(self,x):
    return 1/(1+np.exp(x))
  
  #fit the object with the training data X and y
  def fit(self,X,y):
    nx = len(X[0]) # no of features
    m = len(X)    #no of training examples

    #intitialize all weights to zero
    for i in range(nx):
      self.weights.append(random.randint(-10,10))
    self.b = random.randint(-10,10)

    for t in range(self.num_iter): #loop unitil the number of interation provided by user
      
      #variable intialization
      z = list()
      a = list()
      J = 0
      dw = list()
      db = 0
      
      for i in range(m):
       
        z.append(np.dot(X[i],self.weights) + self.b)
        a.append(self.__sigmoid(z[i]))
        J = J +  (- ((y[i]*np.log(a[i]))))
        dz = a[i]-y[i]
        
        for j in range(nx):
          if (i==0):
            dw.append((X[i][j] * dz))
          else:
            dw[j] = dw[j] + (X[i][j] * dz)
        db = db + a[i] - y[i]
      
      for i in range(nx):
         dw[j] = dw[j]/m
      
      J = J/m
      db = db/m
      
      for i in range(len(self.weights)):
         self.weights[i] = self.weights[i] - self.alpha * dw[i] 
      

#main function
feature_x = [[1,2,3],
             [3,4,5],
             [6,7,8]]
result_y = [1,0,1]

lr = LogisticRegression(5,0.1)
lr.fit(feature_x,result_y)

### Vectorization

In [39]:
import time 
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
print(c)
toc = time.time()

print("It took {}ms".format(1000*(toc-tic)))

sum=0
tic1 = time.time()
for i in range(len(a)):
  sum = sum + a[i] * b[i]
print(sum)
toc1 = time.time()

print("It took {}ms".format(1000*(toc1-tic1)))


print("Vectorization is {} times faster".format((toc1-tic1)/(toc-tic)))

250074.12538953198
It took 1.734018325805664ms
250074.12538952183
It took 655.620813369751ms
Vectorization is 378.09335899903755 times faster


## Broadcasting in python

In [88]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
              [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])
# print(A)
# print(A.sum(axis=0))
# print(A.sum(axis=1))

[ 59.  239.  155.4  76.9]
[128.4 165.2 236.7]


# ***Logistic Regression Using Vectorization ***

In [135]:
class VLogisticRegression:
  def __init__(self, num_iter, alpha, verbose = 0):
    self.num_iter = num_iter
    self.alpha = alpha
    self.weights = list()
    self.intercept = 0
  def weights_(self):
    return self.weights
  
  def intercept_(self):
    return self.intercept

  def fit(self,X,y):
    nx = X.shape[1] 
    m = X.shape[0]
    dw = np.random.randn(nx)
    weights = np.random.randn(1,nx)
    b = np.random.randn(1,1)
    
    for i in range(self.num_iter):
      Z = np.dot(weights, X.T) + b
      a = 1/(1+np.exp(-Z))
      dZ = a-y
      db = np.mean(dZ)
      dw = ((dZ.reshape(4,1) * X).sum(axis=0))/m
      weights = weights - (self.alpha * dw)
      b = b- self.alpha * db 
    self.weights = weights
    self.intercept = b 

X = np.array([[1,2,3],
              [4,5,6],
              [8,9,10],
              [11,12,13]])
y = np.array([1,0,1,1])
VLR = VLogisticRegression(5,0.1)
VLR.fit(X,y)
print(VLR.weights_())
print(VLR.intercept_())

[[ 0.56037817  1.31054314 -1.36487725]]
[[-0.39197766]]


In [130]:
## HIT AND TIRAL FOR THE ALOGIRTHM ABOVE

X = np.array([[1,2,3],
              [4,5,6],
              [8,9,10],
              [11,12,13]])
y = np.array([1,0,1,1])
# print(X.shape[1])

weights = np.ones(3)
# print(weights)
b = np.ones(1)
Z = (np.dot(weights,X.T)+b)

a = 1/(1+np.exp(-Z))
# print(Z)
# print(a)
# print(y)
dZ = a-y
dw = (dZ.reshape(4,1)) * X
# print(dw)
dw = (dw.sum(axis=0))
# print(dw)
# print(dw/3)
# print(dz)
print(weights)
weights = weights - 0.1 * (dw)
print(weights)

[1. 1. 1.]
[0.60009115 0.50018227 0.40027338]
